# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: **/*.sln
  buildPlatform: x64
  buildConfiguration: Release
  projectPaths: src/**/*.csproj

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.204'

- task: NuGetToolInstaller@0
  inputs:
    checkLatest: true
    
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      packagesToPack: $(projectPaths)
      nobuild: true