# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  projectPaths: '**/Ofn.ServiceFabric.Cache*.csproj'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.204'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(projectPaths)'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(projectPaths)'
    arguments: '/p:Platform=$(buildPlatform) --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: '$(projectPaths)'
    nobuild: true